# Modifies CodeBuild stage

version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Python version and pip info:"
      - python --version
      - pip --version
      - echo "Upgrading pip..."
      - pip install --upgrade pip
      - echo "Installing dependencies..."
      - export TMPDIR=/var/tmp
      - pip install -r requirements.txt #Add flags to this to change cached dir
  build:
    commands:
      - echo "Build completed"
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  name: flask-app-$(date +%Y-%m-%d)